export const Governorates = [
  { key: "1", value: "Ariana" },
  { key: "2", value: "Béja" },
  { key: "3", value: "Ben Arous" },
  { key: "4", value: "Bizerte" },
  { key: "5", value: "Gabès" },
  { key: "6", value: "Jendouba" },
  { key: "7", value: "Kasserine" },
  { key: "8", value: "Kébili" },
  { key: "9", value: "Le Kef" },
  { key: "10", value: "Mahdia" },
  { key: "11", value: "La Manouba" },
  { key: "12", value: "Médenine" },
  { key: "13", value: "Monastir" },
  { key: "14", value: "Nabeul" },
  { key: "15", value: "Sidi Bouzid" },
  { key: "16", value: "Siliana" },
  { key: "17", value: "Sousse" },
  { key: "18", value: "Tataouine" },
  { key: "19", value: "Tozeur" },
  { key: "20", value: "Tunis" },
  { key: "21", value: "Zaghouan" },
  { key: "22", value: "Sousse" },
  { key: "23", value: "Tataouine" },
  { key: "23", value: "Gafsa" }
];
